# Generated by Django 5.2.17 on 2026-10-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptop_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('purchase_processing', 'Purchase Processing'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('purchase_completed', 'Purchase Completed')], default='approved', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='laptop_requests.laptoprequest')),
            ],
        ),
    ]
