# Generated by Django 5.2.17 on 2026-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(choices=[('Laptop Selling', 'Laptop Selling'), ('KYC Verification', 'KYC Verification'), ('Inspection', 'Laptop Inspection'), ('Valuation', 'Valuation'), ('Purchase Status', 'Purchase Status'), ('Other', 'Other Enquiry')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
