# Generated by Django 5.2.17 on 2026-10-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptop_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_condition', models.CharField(max_length=100)),
                ('screen_condition', models.CharField(max_length=100)),
                ('keyboard_condition', models.CharField(max_length=100)),
                ('battery_condition', models.CharField(max_length=100)),
                ('charger_condition', models.CharField(max_length=100)),
                ('camera_condition', models.CharField(max_length=100)),
                ('speaker_condition', models.CharField(max_length=100)),
                ('ports_condition', models.CharField(max_length=100)),
                ('processor_verified', models.BooleanField(default=False)),
                ('ram_verified', models.BooleanField(default=False)),
                ('storage_verified', models.BooleanField(default=False)),
                ('overall_condition', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('suggested_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inspection_status', models.CharField(default='completed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='laptop_requests.laptoprequest')),
            ],
        ),
    ]
