# Generated by Django 5.2.17 on 2026-10-05 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptop_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_proof', models.FileField(upload_to='kyc/identity/')),
                ('address_proof', models.FileField(upload_to='kyc/address/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='kyc/additional/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_verification', 'Under Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='laptop_requests.laptoprequest')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
