# Generated by Django 5.2.17 on 2026-10-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=150)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('purchase_year', models.PositiveIntegerField()),
                ('original_purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_repair', 'Needs Repair')], max_length=30)),
                ('reason_for_selling', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('kyc_verification', 'KYC Verification'), ('inspection_pending', 'Inspection Pending'), ('inspector_assigned', 'Inspector Assigned'), ('inspection_completed', 'Inspection Completed'), ('valuation_pending', 'Valuation Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('purchase_processing', 'Purchase Processing'), ('purchase_completed', 'Purchase Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
