# Generated by Django 5.2.17 on 2026-10-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoprequest',
            name='offer_decision',
            field=models.CharField(choices=[('pending', 'Pending seller decision'), ('accepted', 'Accepted'), ('rejected', 'Declined by seller')], default='pending', max_length=20),
        ),
    ]
